<?php
/** @var Magento\Framework\View\Element\Template $block */
/** @var Magento\Framework\Escaper $escaper */
/** @var Bootcamp\BookmarkCustomer\ViewModel\Bookmark $bookmarks */
$bookmarks = $block->getData('bookmark_model');


?>

<table>
    <tbody>
    <?php foreach ($bookmarks->getCustomerList() as $bookmark): ?>
        <tr>
            <td><?= $bookmark->getData('page_title') ?></td>
            <td><a href="<?= $bookmark->getData('url_page') ?>"><?= $bookmark->getData('url_page') ?></a></td>
            </tr>
    <?php endforeach ?>
    </tbody>
</table>

<div class="message info empty">
    <span><?= $escaper->escapeHtml(__('You do not have any bookmark')) ?></span>
</div>
